### ISSUE TITLE
Publish on CTAN?

### ISSUE THREAD

**Issue by kir0ul** [PM25/SimpleDarkBlue-BeamerTheme#1]
Hi there,

This Beamer theme looks great, thanks for that! :heart: 

I was wondering if you would consider to publish it on [CTAN](https://ctan.org/) so that it'll become available on TeX distributions like TeX Live?

Some references in case it's useful:
1. https://ctan.org/upload
2. https://ctan.org/help/upload-pkg

**Comment by pm25** [comment]
I have published it on CTAN, here is the link:
[https://ctan.org/pkg/beamertheme-simpledarkblue](https://ctan.org/pkg/beamertheme-simpledarkblue)

Thanks for your advice!
