### ISSUE TITLE
Consider adding a LICENSE file in the repository

### ISSUE THREAD

**Issue by jorgepiloto** [PM25/SimpleDarkBlue-BeamerTheme#2]
I really like this elegant and simple theme for Beamer presentations. From the [CTAN archive](https://ctan.org/pkg/beamertheme-simpledarkblue) I see this holds a GNU Public License but this repository does not point it out.

Hence, I was wondering if a copy of that license could be applied to this repo. If you want @PM25, I can open a pull request on this.

Anyway, thank you for developing this awesome theme 🚀

**Comment by pm25** [comment]
Yeah, no problem.
I have added the license.
Thanks for the notification!

**Comment by jorgepiloto** [comment]
So cool! Thanks 🙌🏽
